'''
Created on unknown

@author: Mask Shift converter
'''

class TMC4672_fields(object):

	SI_TYPE_MASK                                = 0xFFFFFFFF # CHIPINFO_DATA
	SI_TYPE_SHIFT                               = 0
	SI_VERSION_MASK                             = 0xFFFFFFFF # CHIPINFO_DATA
	SI_VERSION_SHIFT                            = 0
	SI_DATE_MASK                                = 0xFFFFFFFF # CHIPINFO_DATA
	SI_DATE_SHIFT                               = 0
	SI_TIME_MASK                                = 0xFFFFFFFF # CHIPINFO_DATA
	SI_TIME_SHIFT                               = 0
	SI_VARIANT_MASK                             = 0xFFFFFFFF # CHIPINFO_DATA
	SI_VARIANT_SHIFT                            = 0
	SI_BUILD_MASK                               = 0xFFFFFFFF # CHIPINFO_DATA
	SI_BUILD_SHIFT                              = 0
	CHIP_INFO_ADDRESS_MASK                      = 0xFF # CHIPINFO_ADDR
	CHIP_INFO_ADDRESS_SHIFT                     = 0
	ADC_I0_RAW_MASK                             = 0xFFFF # ADC_RAW_DATA
	ADC_I0_RAW_SHIFT                            = 0
	ADC_I1_RAW_MASK                             = 0xFFFF0000 # ADC_RAW_DATA
	ADC_I1_RAW_SHIFT                            = 16
	ADC_VM_RAW_MASK                             = 0xFFFF # ADC_RAW_DATA
	ADC_VM_RAW_SHIFT                            = 0
	ADC_AGPI_A_RAW_MASK                         = 0xFFFF0000 # ADC_RAW_DATA
	ADC_AGPI_A_RAW_SHIFT                        = 16
	ADC_AENC_UX_RAW_MASK                        = 0xFFFF # ADC_RAW_DATA
	ADC_AENC_UX_RAW_SHIFT                       = 0
	ADC_AENC_WY_RAW_MASK                        = 0xFFFF0000 # ADC_RAW_DATA
	ADC_AENC_WY_RAW_SHIFT                       = 16
	ADC_AENC_VN_RAW_MASK                        = 0xFFFF # ADC_RAW_DATA
	ADC_AENC_VN_RAW_SHIFT                       = 0
	ADC_AGPI_B_RAW_MASK                         = 0xFFFF0000 # ADC_RAW_DATA
	ADC_AGPI_B_RAW_SHIFT                        = 16
	ADC_RAW_ADDR_MASK                           = 0xFF # ADC_RAW_ADDR
	ADC_RAW_ADDR_SHIFT                          = 0
	CFG_DSMODULATOR_A_MASK                      = 0x03 # ADC_CONFIG_DATA
	CFG_DSMODULATOR_A_SHIFT                     = 0
	MCLK_POLARITY_A_MASK                        = 0x04 # ADC_CONFIG_DATA
	MCLK_POLARITY_A_SHIFT                       = 2
	MDAT_POLARITY_A_MASK                        = 0x08 # ADC_CONFIG_DATA
	MDAT_POLARITY_A_SHIFT                       = 3
	SEL_NCLK_MCLK_I_A_MASK                      = 0x10 # ADC_CONFIG_DATA
	SEL_NCLK_MCLK_I_A_SHIFT                     = 4
	BLANKING_A_MASK                             = 0xFF00 # ADC_CONFIG_DATA
	BLANKING_A_SHIFT                            = 8
	CFG_DSMODULATOR_B_MASK                      = 0x30000 # ADC_CONFIG_DATA
	CFG_DSMODULATOR_B_SHIFT                     = 16
	MCLK_POLARITY_B_MASK                        = 0x40000 # ADC_CONFIG_DATA
	MCLK_POLARITY_B_SHIFT                       = 18
	MDAT_POLARITY_B_MASK                        = 0x80000 # ADC_CONFIG_DATA
	MDAT_POLARITY_B_SHIFT                       = 19
	SEL_NCLK_MCLK_I_B_MASK                      = 0x100000 # ADC_CONFIG_DATA
	SEL_NCLK_MCLK_I_B_SHIFT                     = 20
	BLANKING_B_MASK                             = 0xFF000000 # ADC_CONFIG_DATA
	BLANKING_B_SHIFT                            = 24
	DSADC_MCLK_A_MASK                           = 0xFF # ADC_CONFIG_DATA
	DSADC_MCLK_A_SHIFT                          = 0
	DSADC_MCLK_B_MASK                           = 0xFF0000 # ADC_CONFIG_DATA
	DSADC_MCLK_B_SHIFT                          = 16
	DSADC_MDEC_A_MASK                           = 0xFFFF # ADC_CONFIG_DATA
	DSADC_MDEC_A_SHIFT                          = 0
	DSADC_MDEC_B_MASK                           = 0xFFFF0000 # ADC_CONFIG_DATA
	DSADC_MDEC_B_SHIFT                          = 16
	ADC_I0_MASK                                 = 0x0F # ADC_CONFIG_DATA
	ADC_I0_SHIFT                                = 0
	ADC_I1_MASK                                 = 0xF0 # ADC_CONFIG_DATA
	ADC_I1_SHIFT                                = 4
	ADC_VM_MASK                                 = 0xF00 # ADC_CONFIG_DATA
	ADC_VM_SHIFT                                = 8
	ADC_AGPI_A_MASK                             = 0xF000 # ADC_CONFIG_DATA
	ADC_AGPI_A_SHIFT                            = 12
	ADC_AGPI_B_MASK                             = 0xF0000 # ADC_CONFIG_DATA
	ADC_AGPI_B_SHIFT                            = 16
	ADC_AENC_UX_MASK                            = 0xF00000 # ADC_CONFIG_DATA
	ADC_AENC_UX_SHIFT                           = 20
	ADC_AENC_VN_MASK                            = 0xF000000 # ADC_CONFIG_DATA
	ADC_AENC_VN_SHIFT                           = 24
	ADC_AENC_WY_MASK                            = 0xF0000000 # ADC_CONFIG_DATA
	ADC_AENC_WY_SHIFT                           = 28
	ADC_I0_GAIN_MASK                            = 0x03 # ADC_CONFIG_DATA
	ADC_I0_GAIN_SHIFT                           = 0
	ADC_I1_GAIN_MASK                            = 0x0C # ADC_CONFIG_DATA
	ADC_I1_GAIN_SHIFT                           = 2
	ADC_VM_GAIN_MASK                            = 0x30 # ADC_CONFIG_DATA
	ADC_VM_GAIN_SHIFT                           = 4
	ADC_AGPI_A_GAIN_MASK                        = 0xC0 # ADC_CONFIG_DATA
	ADC_AGPI_A_GAIN_SHIFT                       = 6
	ADC_AGPI_B_GAIN_MASK                        = 0x300 # ADC_CONFIG_DATA
	ADC_AGPI_B_GAIN_SHIFT                       = 8
	ADC_AENC_UX_GAIN_MASK                       = 0xC00 # ADC_CONFIG_DATA
	ADC_AENC_UX_GAIN_SHIFT                      = 10
	ADC_AENC_VN_GAIN_MASK                       = 0x3000 # ADC_CONFIG_DATA
	ADC_AENC_VN_GAIN_SHIFT                      = 12
	ADC_AENC_WY_GAIN_MASK                       = 0xC000 # ADC_CONFIG_DATA
	ADC_AENC_WY_GAIN_SHIFT                      = 14
	USE_SNH_FOR_GROUP_A_MASK                    = 0x10000 # ADC_CONFIG_DATA
	USE_SNH_FOR_GROUP_A_SHIFT                   = 16
	USE_SNH_FOR_GROUP_B_MASK                    = 0x20000 # ADC_CONFIG_DATA
	USE_SNH_FOR_GROUP_B_SHIFT                   = 17
	USE_PAD_AGPI_B_FOR_AGPI_A_MASK              = 0x40000 # ADC_CONFIG_DATA
	USE_PAD_AGPI_B_FOR_AGPI_A_SHIFT             = 18
	ENABLE_ADC_I0_MASK                          = 0x80000 # ADC_CONFIG_DATA
	ENABLE_ADC_I0_SHIFT                         = 19
	ENABLE_ADC_I1_MASK                          = 0x100000 # ADC_CONFIG_DATA
	ENABLE_ADC_I1_SHIFT                         = 20
	ENABLE_ADC_VM_MASK                          = 0x200000 # ADC_CONFIG_DATA
	ENABLE_ADC_VM_SHIFT                         = 21
	ENABLE_ADC_AGPI_A_MASK                      = 0x400000 # ADC_CONFIG_DATA
	ENABLE_ADC_AGPI_A_SHIFT                     = 22
	ENABLE_ADC_AGPI_B_MASK                      = 0x800000 # ADC_CONFIG_DATA
	ENABLE_ADC_AGPI_B_SHIFT                     = 23
	ENABLE_ADC_AENC_UX_MASK                     = 0x1000000 # ADC_CONFIG_DATA
	ENABLE_ADC_AENC_UX_SHIFT                    = 24
	ENABLE_ADC_AENC_VN_MASK                     = 0x2000000 # ADC_CONFIG_DATA
	ENABLE_ADC_AENC_VN_SHIFT                    = 25
	ENABLE_ADC_AENC_WY_MASK                     = 0x4000000 # ADC_CONFIG_DATA
	ENABLE_ADC_AENC_WY_SHIFT                    = 26
	PULSE_LENGTH_SNH_A_0_MASK                   = 0xFF # ADC_CONFIG_DATA
	PULSE_LENGTH_SNH_A_0_SHIFT                  = 0
	PULSE_LENGTH_SNH_A_1_MASK                   = 0xFF00 # ADC_CONFIG_DATA
	PULSE_LENGTH_SNH_A_1_SHIFT                  = 8
	PULSE_LENGTH_SNH_B_0_MASK                   = 0xFF0000 # ADC_CONFIG_DATA
	PULSE_LENGTH_SNH_B_0_SHIFT                  = 16
	PULSE_LENGTH_SNH_B_1_MASK                   = 0xFF000000 # ADC_CONFIG_DATA
	PULSE_LENGTH_SNH_B_1_SHIFT                  = 24
	ADC_I_UX_SELECT_MASK                        = 0x03 # ADC_CONFIG_DATA
	ADC_I_UX_SELECT_SHIFT                       = 0
	ADC_I_V_SELECT_MASK                         = 0x0C # ADC_CONFIG_DATA
	ADC_I_V_SELECT_SHIFT                        = 2
	ADC_I_WY_SELECT_MASK                        = 0x30 # ADC_CONFIG_DATA
	ADC_I_WY_SELECT_SHIFT                       = 4
	ADC_I_SOURCE_SELECT_MASK                    = 0x40 # ADC_CONFIG_DATA
	ADC_I_SOURCE_SELECT_SHIFT                   = 6
	ADC_I_MEASUREMENT_MODE_MASK                 = 0x380 # ADC_CONFIG_DATA
	ADC_I_MEASUREMENT_MODE_SHIFT                = 7
	ADC_TRIGGER_SELECT_MASK                     = 0x400 # ADC_CONFIG_DATA
	ADC_TRIGGER_SELECT_SHIFT                    = 10
	ADC_I0_OFFSET_MASK                          = 0xFFFF # ADC_CONFIG_DATA
	ADC_I0_OFFSET_SHIFT                         = 0
	ADC_I0_SCALE_MASK                           = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_I0_SCALE_SHIFT                          = 16
	ADC_I1_OFFSET_MASK                          = 0xFFFF # ADC_CONFIG_DATA
	ADC_I1_OFFSET_SHIFT                         = 0
	ADC_I1_SCALE_MASK                           = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_I1_SCALE_SHIFT                          = 16
	ADC_I2_OFFSET_MASK                          = 0xFFFF # ADC_CONFIG_DATA
	ADC_I2_OFFSET_SHIFT                         = 0
	ADC_I2_SCALE_MASK                           = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_I2_SCALE_SHIFT                          = 16
	PWM_SWITCH_LIMIT_MASK                       = 0xFFFF # ADC_CONFIG_DATA
	PWM_SWITCH_LIMIT_SHIFT                      = 0
	ADC_VM_OFFSET_MASK                          = 0xFFFF # ADC_CONFIG_DATA
	ADC_VM_OFFSET_SHIFT                         = 0
	ADC_VM_SCALE_MASK                           = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_VM_SCALE_SHIFT                          = 16
	AENC_0_SELECT_MASK                          = 0x03 # ADC_CONFIG_DATA
	AENC_0_SELECT_SHIFT                         = 0
	AENC_1_SELECT_MASK                          = 0x0C # ADC_CONFIG_DATA
	AENC_1_SELECT_SHIFT                         = 2
	AENC_2_SELECT_MASK                          = 0xC0 # ADC_CONFIG_DATA
	AENC_2_SELECT_SHIFT                         = 4
	ADC_AENC_UX_OFFSET_MASK                     = 0xFFFF # ADC_CONFIG_DATA
	ADC_AENC_UX_OFFSET_SHIFT                    = 0
	ADC_AENC_UX_SCALE_MASK                      = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_AENC_UX_SCALE_SHIFT                     = 16
	ADC_AENC_VN_OFFSET_MASK                     = 0xFFFF # ADC_CONFIG_DATA
	ADC_AENC_VN_OFFSET_SHIFT                    = 0
	AADC_AENC_VN_SCALE_MASK                     = 0xFFFF0000 # ADC_CONFIG_DATA
	AADC_AENC_VN_SCALE_SHIFT                    = 16
	ADC_AENC_WY_OFFSET_MASK                     = 0xFFFF # ADC_CONFIG_DATA
	ADC_AENC_WY_OFFSET_SHIFT                    = 0
	ADC_AENC_WY_SCALE_MASK                      = 0xFFFF0000 # ADC_CONFIG_DATA
	ADC_AENC_WY_SCALE_SHIFT                     = 16
	ADC_IUX_MASK                                = 0xFFFF # ADC_IWY_IUX
	ADC_IUX_SHIFT                               = 0
	ADC_IWY_MASK                                = 0xFFFF0000 # ADC_IWY_IUX
	ADC_IWY_SHIFT                               = 16
	ADC_IV_MASK                                 = 0xFFFF0000 # ADC_IV_VM
	ADC_IV_SHIFT                                = 16
	AENC_UX_MASK                                = 0xFFFF # AENC_WY_UX
	AENC_UX_SHIFT                               = 0
	AENC_WY_MASK                                = 0xFFFF0000 # AENC_WY_UX
	AENC_WY_SHIFT                               = 16
	AENC_VN_MASK                                = 0xFFFF # AENC_VN
	AENC_VN_SHIFT                               = 0
	PWM_POLARITIES_0_MASK                       = 0x01 # PWM_POLARITIES
	PWM_POLARITIES_0_SHIFT                      = 0
	PWM_POLARITIES_1_MASK                       = 0x02 # PWM_POLARITIES
	PWM_POLARITIES_1_SHIFT                      = 1
	PWM_MAXCOUNT_MASK                           = 0xFFFF # PWM_MAXCOUNT
	PWM_MAXCOUNT_SHIFT                          = 0
	PWM_BBM_L_MASK                              = 0xFF # PWM_BBM_H_BBM_L
	PWM_BBM_L_SHIFT                             = 0
	PWM_BBM_H_MASK                              = 0xFF00 # PWM_BBM_H_BBM_L
	PWM_BBM_H_SHIFT                             = 8
	PWM_CHOP_MASK                               = 0xFF # PWM_SV_CHOP
	PWM_CHOP_SHIFT                              = 0
	PWM_SV_MASK                                 = 0x300 # PWM_SV_CHOP
	PWM_SV_SHIFT                                = 8
	N_POLE_PAIRS_MASK                           = 0xFFFF # MOTOR_TYPE_N_POLE_PAIRS
	N_POLE_PAIRS_SHIFT                          = 0
	MOTOR_TYPE_MASK                             = 0xFF0000 # MOTOR_TYPE_N_POLE_PAIRS
	MOTOR_TYPE_SHIFT                            = 16
	ADC_I0_EXT_MASK                             = 0xFFFF # ADC_I1_I0_EXT
	ADC_I0_EXT_SHIFT                            = 0
	ADC_I1_EXT_MASK                             = 0xFFFF0000 # ADC_I1_I0_EXT
	ADC_I1_EXT_SHIFT                            = 16
	PHI_E_EXT_MASK                              = 0xFFFF # PHI_E_EXT
	PHI_E_EXT_SHIFT                             = 0
	PHI_M_EXT_MASK                              = 0xFFFF # PHI_M_EXT
	PHI_M_EXT_SHIFT                             = 0
	POSITION_EXT_MASK                           = 0xFFFFFFFF # POSITION_EXT
	POSITION_EXT_SHIFT                          = 0
	OPENLOOP_PHI_DIRECTION_MASK                 = 0x1000 # OPENLOOP_MODE
	OPENLOOP_PHI_DIRECTION_SHIFT                = 12
	OPENLOOP_ACCELERATION_MASK                  = 0xFFFFFFFF # OPENLOOP_ACCELERATION
	OPENLOOP_ACCELERATION_SHIFT                 = 0
	OPENLOOP_VELOCITY_TARGET_MASK               = 0xFFFFFFFF # OPENLOOP_VELOCITY_TARGET
	OPENLOOP_VELOCITY_TARGET_SHIFT              = 0
	OPENLOOP_VELOCITY_ACTUAL_MASK               = 0xFFFFFFFF # OPENLOOP_VELOCITY_ACTUAL
	OPENLOOP_VELOCITY_ACTUAL_SHIFT              = 0
	PHI_OPENLOOP_MASK                           = 0xFFFF # PHI_OPENLOOP
	PHI_OPENLOOP_SHIFT                          = 0
	UD_EXT_MASK                                 = 0xFFFF # UQ_UD_EXT
	UD_EXT_SHIFT                                = 0
	UQ_EXT_MASK                                 = 0xFFFF0000 # UQ_UD_EXT
	UQ_EXT_SHIFT                                = 16
	APOL_MASK                                   = 0x01 # POS_FB_CONFIG_DATA
	APOL_SHIFT                                  = 0
	BPOL_MASK                                   = 0x02 # POS_FB_CONFIG_DATA
	BPOL_SHIFT                                  = 1
	NPOL_MASK                                   = 0x04 # POS_FB_CONFIG_DATA
	NPOL_SHIFT                                  = 2
	USE_ABN_AS_N_MASK                           = 0x08 # POS_FB_CONFIG_DATA
	USE_ABN_AS_N_SHIFT                          = 3
	CLN_MASK                                    = 0x100 # POS_FB_CONFIG_DATA
	CLN_SHIFT                                   = 8
	DIRECTION_MASK                              = 0x1000 # POS_FB_CONFIG_DATA
	DIRECTION_SHIFT                             = 12
	ABN_DECODER_PPR_MASK                        = 0xFFFFFF # POS_FB_CONFIG_DATA
	ABN_DECODER_PPR_SHIFT                       = 0
	ABN_DECODER_PHI_M_OFFSET_MASK               = 0xFFFF # POS_FB_CONFIG_DATA
	ABN_DECODER_PHI_M_OFFSET_SHIFT              = 0
	ABN_DECODER_PHI_E_OFFSET_MASK               = 0xFFFF0000 # POS_FB_CONFIG_DATA
	ABN_DECODER_PHI_E_OFFSET_SHIFT              = 16
	ABN_DECODER_ERROR_PHASE_MASK                = 0xFFFF # POS_FB_CONFIG_DATA
	ABN_DECODER_ERROR_PHASE_SHIFT               = 0
	ABN_DECODER_ERROR_AMPL_MASK                 = 0xFFFF0000 # POS_FB_CONFIG_DATA
	ABN_DECODER_ERROR_AMPL_SHIFT                = 16
	ABN_2_DECODER_PPR_MASK                      = 0xFFFFFF # POS_FB_CONFIG_DATA
	ABN_2_DECODER_PPR_SHIFT                     = 0
	ABN_2_DECODER_PHI_M_OFFSET_MASK             = 0xFFFF # POS_FB_CONFIG_DATA
	ABN_2_DECODER_PHI_M_OFFSET_SHIFT            = 0
	POLARITY_MASK                               = 0x01 # POS_FB_CONFIG_DATA
	POLARITY_SHIFT                              = 0
	INTERPOLATION_MASK                          = 0x02 # POS_FB_CONFIG_DATA
	INTERPOLATION_SHIFT                         = 1
	HALL_ORDER_MASK                             = 0x38 # POS_FB_CONFIG_DATA
	HALL_ORDER_SHIFT                            = 3
	HALL_BLANK_MASK                             = 0xFFF0000 # POS_FB_CONFIG_DATA
	HALL_BLANK_SHIFT                            = 16
	HALL_POSITION_000_MASK                      = 0xFFFF # POS_FB_CONFIG_DATA
	HALL_POSITION_000_SHIFT                     = 0
	HALL_POSITION_060_MASK                      = 0xFFFF0000 # POS_FB_CONFIG_DATA
	HALL_POSITION_060_SHIFT                     = 16
	HALL_POSITION_120_MASK                      = 0xFFFF # POS_FB_CONFIG_DATA
	HALL_POSITION_120_SHIFT                     = 0
	HALL_POSITION_180_MASK                      = 0xFFFF0000 # POS_FB_CONFIG_DATA
	HALL_POSITION_180_SHIFT                     = 16
	HALL_POSITION_240_MASK                      = 0xFFFF # POS_FB_CONFIG_DATA
	HALL_POSITION_240_SHIFT                     = 0
	HALL_POSITION_300_MASK                      = 0xFFFF0000 # POS_FB_CONFIG_DATA
	HALL_POSITION_300_SHIFT                     = 16
	HALL_PHI_M_OFFSET_MASK                      = 0xFFFF # POS_FB_CONFIG_DATA
	HALL_PHI_M_OFFSET_SHIFT                     = 0
	HALL_PHI_E_OFFSET_MASK                      = 0xFFFF0000 # POS_FB_CONFIG_DATA
	HALL_PHI_E_OFFSET_SHIFT                     = 16
	HALL_DPHI_MAX_MASK                          = 0xFFFF # POS_FB_CONFIG_DATA
	HALL_DPHI_MAX_SHIFT                         = 0
	AENC_DECODER_MODE_0_MASK                    = 0x01 # POS_FB_CONFIG_DATA
	AENC_DECODER_MODE_0_SHIFT                   = 0
	AENC_DECODER_MODE_12_MASK                   = 0x1000 # POS_FB_CONFIG_DATA
	AENC_DECODER_MODE_12_SHIFT                  = 12
	AENC_DECODER_N_THRESHOLD_MASK               = 0xFFFF # POS_FB_CONFIG_DATA
	AENC_DECODER_N_THRESHOLD_SHIFT              = 0
	AENC_DECODER_N_PULSE_POLARITY_MASK          = 0x10000 # POS_FB_CONFIG_DATA
	AENC_DECODER_N_PULSE_POLARITY_SHIFT         = 16
	AENC_DECODER_PPR_MASK                       = 0xFFFF # POS_FB_CONFIG_DATA
	AENC_DECODER_PPR_SHIFT                      = 0
	AENC_DECODER_PHI_M_OFFSET_MASK              = 0xFFFF # POS_FB_CONFIG_DATA
	AENC_DECODER_PHI_M_OFFSET_SHIFT             = 0
	AENC_DECODER_PHI_E_OFFSET_MASK              = 0xFFFF0000 # POS_FB_CONFIG_DATA
	AENC_DECODER_PHI_E_OFFSET_SHIFT             = 16
	TRANSACT_DONE_MASK                          = 0x01 # POS_FB_CONFIG_DATA
	TRANSACT_DONE_SHIFT                         = 0
	TRANSACT_IN_PROGRESS_MASK                   = 0x02 # POS_FB_CONFIG_DATA
	TRANSACT_IN_PROGRESS_SHIFT                  = 1
	CCU_ERROR_MASK                              = 0x04 # POS_FB_CONFIG_DATA
	CCU_ERROR_SHIFT                             = 2
	ENABLE_SPI_MASTER_MASK                      = 0x01 # POS_FB_CONFIG_DATA
	ENABLE_SPI_MASTER_SHIFT                     = 0
	START_NSTOP_MASK                            = 0x02 # POS_FB_CONFIG_DATA
	START_NSTOP_SHIFT                           = 1
	SCLK_PHASE_MASK                             = 0x10 # POS_FB_CONFIG_DATA
	SCLK_PHASE_SHIFT                            = 4
	SCLK_POLARITY_MASK                          = 0x20 # POS_FB_CONFIG_DATA
	SCLK_POLARITY_SHIFT                         = 5
	CS_POLARITY_MASK                            = 0x40 # POS_FB_CONFIG_DATA
	CS_POLARITY_SHIFT                           = 6
	LSBFIRST_NMSBFIRST_MASK                     = 0x80 # POS_FB_CONFIG_DATA
	LSBFIRST_NMSBFIRST_SHIFT                    = 7
	DATA_SIZE_SELECT_0_MASK                     = 0xFF0000 # POS_FB_CONFIG_DATA
	DATA_SIZE_SELECT_0_SHIFT                    = 16
	DATA_SIZE_SELECT_1_MASK                     = 0xFF000000 # POS_FB_CONFIG_DATA
	DATA_SIZE_SELECT_1_SHIFT                    = 24
	SPI_MASTER_CLK_DIVIDER_MASK                 = 0xFF # POS_FB_CONFIG_DATA
	SPI_MASTER_CLK_DIVIDER_SHIFT                = 0
	WAIT_CYCLES_FOR_CS_MASK                     = 0xFF00 # POS_FB_CONFIG_DATA
	WAIT_CYCLES_FOR_CS_SHIFT                    = 8
	WAIT_CYCLES_T2T_MASK                        = 0xFF0000 # POS_FB_CONFIG_DATA
	WAIT_CYCLES_T2T_SHIFT                       = 8
	TRANSACTION_TYPE_MASK                       = 0x07 # POS_FB_CONFIG_DATA
	TRANSACTION_TYPE_SHIFT                      = 0
	SPI_MASTER_STROBE_MASK_0_MASK               = 0x08 # POS_FB_CONFIG_DATA
	SPI_MASTER_STROBE_MASK_0_SHIFT              = 0
	SPI_MASTER_STROBE_MASK_1_MASK               = 0x10 # POS_FB_CONFIG_DATA
	SPI_MASTER_STROBE_MASK_1_SHIFT              = 0
	SPI_MASTER_STROBE_MASK_2_MASK               = 0x20 # POS_FB_CONFIG_DATA
	SPI_MASTER_STROBE_MASK_2_SHIFT              = 0
	SPI_ENC_MASK_HW_MASK                        = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_ENC_MASK_HW_SHIFT                       = 0
	SPI_ENC_MASK_LW_MASK                        = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_ENC_MASK_LW_SHIFT                       = 0
	SPI_ENC_SHIFT_MASK                          = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_ENC_SHIFT_SHIFT                         = 0
	SPI_ENC_CCU_COMP_VAL_HW_MASK                = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_ENC_CCU_COMP_VAL_HW_SHIFT               = 0
	SPI_ENC_CCU_COMP_VAL_LW_MASK                = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_ENC_CCU_COMP_VAL_LW_SHIFT               = 0
	SPI_MASTER_WR_BUFF_0_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_WR_BUFF_0_SHIFT                  = 0
	SPI_MASTER_WR_BUFF_1_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_WR_BUFF_1_SHIFT                  = 0
	SPI_MASTER_WR_BUFF_2_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_WR_BUFF_2_SHIFT                  = 0
	SPI_MASTER_WR_BUFF_3_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_WR_BUFF_3_SHIFT                  = 0
	SPI_MASTER_RD_BUFF_0_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_RD_BUFF_0_SHIFT                  = 0
	SPI_MASTER_RD_BUFF_1_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_RD_BUFF_1_SHIFT                  = 0
	SPI_MASTER_RD_BUFF_2_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_RD_BUFF_2_SHIFT                  = 0
	SPI_MASTER_RD_BUFF_3_MASK                   = 0xFFFFFFFF # POS_FB_CONFIG_DATA
	SPI_MASTER_RD_BUFF_3_SHIFT                  = 0
	SPI_ENCODER_PHI_M_OFFSET_MASK               = 0xFFFF # POS_FB_CONFIG_DATA
	SPI_ENCODER_PHI_M_OFFSET_SHIFT              = 0
	SPI_ENCODER_PHI_E_OFFSET_MASK               = 0xFFFF0000 # POS_FB_CONFIG_DATA
	SPI_ENCODER_PHI_E_OFFSET_SHIFT              = 16
	SPI_ENCODER_ERROR_PHASE_MASK                = 0xFFFF # POS_FB_CONFIG_DATA
	SPI_ENCODER_ERROR_PHASE_SHIFT               = 0
	SPI_ENCODER_ERROR_AMPL_MASK                 = 0xFFFF0000 # POS_FB_CONFIG_DATA
	SPI_ENCODER_ERROR_AMPL_SHIFT                = 16
	POS_FB_CONFIG_ADDR_MASK                     = 0xFF # POS_FB_CONFIG_ADDR
	POS_FB_CONFIG_ADDR_SHIFT                    = 0
	BIQUAD_X_A_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_A_1_SHIFT                          = 0
	BIQUAD_X_A_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_A_2_SHIFT                          = 0
	BIQUAD_X_B_0_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_B_0_SHIFT                          = 0
	BIQUAD_X_B_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_B_1_SHIFT                          = 0
	BIQUAD_X_B_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_B_2_SHIFT                          = 0
	BIQUAD_X_ENABLE_MASK                        = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_X_ENABLE_SHIFT                       = 0
	BIQUAD_V_A_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_A_1_SHIFT                          = 0
	BIQUAD_V_A_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_A_2_SHIFT                          = 0
	BIQUAD_V_B_0_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_B_0_SHIFT                          = 0
	BIQUAD_V_B_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_B_1_SHIFT                          = 0
	BIQUAD_V_B_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_B_2_SHIFT                          = 0
	BIQUAD_V_ENABLE_MASK                        = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_V_ENABLE_SHIFT                       = 0
	BIQUAD_T_A_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_A_1_SHIFT                          = 0
	BIQUAD_T_A_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_A_2_SHIFT                          = 0
	BIQUAD_T_B_0_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_B_0_SHIFT                          = 0
	BIQUAD_T_B_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_B_1_SHIFT                          = 0
	BIQUAD_T_B_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_B_2_SHIFT                          = 0
	BIQUAD_T_ENABLE_MASK                        = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_T_ENABLE_SHIFT                       = 0
	BIQUAD_F_A_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_A_1_SHIFT                          = 0
	BIQUAD_F_A_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_A_2_SHIFT                          = 0
	BIQUAD_F_B_0_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_B_0_SHIFT                          = 0
	BIQUAD_F_B_1_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_B_1_SHIFT                          = 0
	BIQUAD_F_B_2_MASK                           = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_B_2_SHIFT                          = 0
	BIQUAD_F_ENABLE_MASK                        = 0xFFFFFFFF # CONFIG_DATA
	BIQUAD_F_ENABLE_SHIFT                       = 0
	PRBS_AMPLITUDE_MASK                         = 0xFFFFFFFF # CONFIG_DATA
	PRBS_AMPLITUDE_SHIFT                        = 0
	PRBS_DOWN_SAMPLING_RATIO_MASK               = 0xFFFFFFFF # CONFIG_DATA
	PRBS_DOWN_SAMPLING_RATIO_SHIFT              = 0
	PWM_IRQ_ENABLE_MASK                         = 0x01 # CONFIG_DATA
	PWM_IRQ_ENABLE_SHIFT                        = 0
	PWM_C_NPWM_Z_MASK                           = 0x01 # CONFIG_DATA
	PWM_C_NPWM_Z_SHIFT                          = 1
	PWM_IRQ_DOWNSAMPLING_RATIO_MASK             = 0x3FC # CONFIG_DATA
	PWM_IRQ_DOWNSAMPLING_RATIO_SHIFT            = 2
	FEED_FORWARD_VELOCITY_GAIN_MASK             = 0xFFFFFFFF # CONFIG_DATA
	FEED_FORWARD_VELOCITY_GAIN_SHIFT            = 0
	FEED_FORWARD_VELICITY_FILTER_CONSTANT_MASK  = 0xFFFFFFFF # CONFIG_DATA
	FEED_FORWARD_VELICITY_FILTER_CONSTANT_SHIFT = 0
	FEED_FORWARD_TORQUE_GAIN_MASK               = 0xFFFFFFFF # CONFIG_DATA
	FEED_FORWARD_TORQUE_GAIN_SHIFT              = 0
	FEED_FORWARD_TORGUE_FILTER_CONSTANT_MASK    = 0xFFFFFFFF # CONFIG_DATA
	FEED_FORWARD_TORGUE_FILTER_CONSTANT_SHIFT   = 0
	REF_SWITCH_CONFIG_MASK                      = 0xFFFF # CONFIG_DATA
	REF_SWITCH_CONFIG_SHIFT                     = 0
	ENABLE_ENCODER_INIT_HALL_MASK               = 0x01 # CONFIG_DATA
	ENABLE_ENCODER_INIT_HALL_SHIFT              = 0
	DIG_FILTER_CFG_HALL_MASK                    = 0xFF # CONFIG_DATA
	DIG_FILTER_CFG_HALL_SHIFT                   = 0
	DIG_FILTER_CFG_ENC_MASK                     = 0xFF00 # CONFIG_DATA
	DIG_FILTER_CFG_ENC_SHIFT                    = 8
	DIG_FILTER_CFG_ENC2_MASK                    = 0xFF0000 # CONFIG_DATA
	DIG_FILTER_CFG_ENC2_SHIFT                   = 16
	DIG_FILTER_CFG_REFSW_MASK                   = 0xFF000000 # CONFIG_DATA
	DIG_FILTER_CFG_REFSW_SHIFT                  = 24
	USE_NAGPI_A_PWM_I_MASK                      = 0x01 # CONFIG_DATA
	USE_NAGPI_A_PWM_I_SHIFT                     = 0
	SINGLE_PIN_IF_OFFSET_MASK                   = 0xFFFF # CONFIG_DATA
	SINGLE_PIN_IF_OFFSET_SHIFT                  = 0
	SINGLE_PIN_IF_SCALE_MASK                    = 0xFFFF0000 # CONFIG_DATA
	SINGLE_PIN_IF_SCALE_SHIFT                   = 16
	DIG_FILTER_CFG_PWM_I_MASK                   = 0xFF # CONFIG_DATA
	DIG_FILTER_CFG_PWM_I_SHIFT                  = 0
	CONFIG_ADDR_MASK                            = 0xFF # CONFIG_ADDR
	CONFIG_ADDR_SHIFT                           = 0
	ABN_DECODER_COUNT_MASK                      = 0xFFFFFF # ABN_DECODER_COUNT
	ABN_DECODER_COUNT_SHIFT                     = 0
	ABN_DECODER_COUNT_N_MASK                    = 0xFFFFFF # ABN_DECODER_COUNT_N
	ABN_DECODER_COUNT_N_SHIFT                   = 0
	ABN_DECODER_PHI_M_MASK                      = 0xFFFF # ABN_DECODER_PHI_E_PHI_M
	ABN_DECODER_PHI_M_SHIFT                     = 0
	ABN_DECODER_PHI_E_MASK                      = 0xFFFF0000 # ABN_DECODER_PHI_E_PHI_M
	ABN_DECODER_PHI_E_SHIFT                     = 16
	ABN_DECODER_POSITION_MASK                   = 0xFFFFFFFF # ABN_DECODER_POSITION
	ABN_DECODER_POSITION_SHIFT                  = 0
	ABN_2_DECODER_COUNT_MASK                    = 0xFFFFFF # ABN_2_DECODER_COUNT
	ABN_2_DECODER_COUNT_SHIFT                   = 0
	ABN_2_DECODER_COUNT_N_MASK                  = 0xFFFFFF # ABN_2_DECODER_COUNT_N
	ABN_2_DECODER_COUNT_N_SHIFT                 = 0
	ABN_2_DECODER_PHI_M_MASK                    = 0xFFFF # ABN_2_DECODER_PHI_E_PHI_M
	ABN_2_DECODER_PHI_M_SHIFT                   = 0
	ABN_2_DECODER_PHI_E_MASK                    = 0xFFFF0000 # ABN_2_DECODER_PHI_E_PHI_M
	ABN_2_DECODER_PHI_E_SHIFT                   = 16
	ABN_2_DECODER_POSITION_MASK                 = 0xFFFFFFFF # ABN_2_DECODER_POSITION
	ABN_2_DECODER_POSITION_SHIFT                = 0
	HALL_PHI_E_MASK                             = 0xFFFF # HALL_PHI_E_INTERPOLATED_PHI_E
	HALL_PHI_E_SHIFT                            = 0
	HALL_PHI_E_INTERPOLATED_MASK                = 0xFFFF0000 # HALL_PHI_E_INTERPOLATED_PHI_E
	HALL_PHI_E_INTERPOLATED_SHIFT               = 16
	HALL_PHI_M_MASK                             = 0xFFFF # HALL_PHI_M
	HALL_PHI_M_SHIFT                            = 0
	AENC_DECODER_COUNT_MASK                     = 0xFFFFFFFF # AENC_DECODER_COUNT
	AENC_DECODER_COUNT_SHIFT                    = 0
	AENC_DECODER_COUNT_N_MASK                   = 0xFFFFFFFF # AENC_DECODER_COUNT_N
	AENC_DECODER_COUNT_N_SHIFT                  = 0
	AENC_DECODER_PHI_M_MASK                     = 0xFFFF # AENC_DECODER_PHI_E_PHI_M
	AENC_DECODER_PHI_M_SHIFT                    = 0
	AENC_DECODER_PHI_E_MASK                     = 0xFFFF0000 # AENC_DECODER_PHI_E_PHI_M
	AENC_DECODER_PHI_E_SHIFT                    = 16
	AENC_DECODER_POSITION_MASK                  = 0xFFFFFFFF # AENC_DECODER_POSITION
	AENC_DECODER_POSITION_SHIFT                 = 0
	SPI_ENCODER_PHI_M_MASK                      = 0xFFFF # SPI_ENCODER_PHI_E_PHI_M
	SPI_ENCODER_PHI_M_SHIFT                     = 0
	SPI_ENCODER_PHI_E_MASK                      = 0xFFFF0000 # SPI_ENCODER_PHI_E_PHI_M
	SPI_ENCODER_PHI_E_SHIFT                     = 16
	STATUS_STOP_L_MASK                          = 0x01 # RAMP_STATUS
	STATUS_STOP_L_SHIFT                         = 0
	STATUS_STOP_R_MASK                          = 0x02 # RAMP_STATUS
	STATUS_STOP_R_SHIFT                         = 1
	STATUS_LATCH_L_MASK                         = 0x04 # RAMP_STATUS
	STATUS_LATCH_L_SHIFT                        = 2
	STATUS_LATCH_R_MASK                         = 0x08 # RAMP_STATUS
	STATUS_LATCH_R_SHIFT                        = 3
	EVENT_STOP_L_MASK                           = 0x10 # RAMP_STATUS
	EVENT_STOP_L_SHIFT                          = 4
	EVENT_STOP_R_MASK                           = 0x20 # RAMP_STATUS
	EVENT_STOP_R_SHIFT                          = 5
	EVENT_STOP_SG_MASK                          = 0x40 # RAMP_STATUS
	EVENT_STOP_SG_SHIFT                         = 6
	EVENT_POS_REACHED_MASK                      = 0x80 # RAMP_STATUS
	EVENT_POS_REACHED_SHIFT                     = 7
	VELOCITY_REACHED_MASK                       = 0x100 # RAMP_STATUS
	VELOCITY_REACHED_SHIFT                      = 8
	POSITION_REACHED_MASK                       = 0x200 # RAMP_STATUS
	POSITION_REACHED_SHIFT                      = 9
	VZERO_MASK                                  = 0x400 # RAMP_STATUS
	VZERO_SHIFT                                 = 10
	T_ZEROWAIT_ACTIVE_MASK                      = 0x800 # RAMP_STATUS
	T_ZEROWAIT_ACTIVE_SHIFT                     = 11
	SECOND_MOVE_MASK                            = 0x1000 # RAMP_STATUS
	SECOND_MOVE_SHIFT                           = 12
	STATUS_SG_MASK                              = 0x2000 # RAMP_STATUS
	STATUS_SG_SHIFT                             = 13
	RAMP_A1_MASK                                = 0xFFFF # RAMP_AMAX_A1
	RAMP_A1_SHIFT                               = 0
	RAMP_AMAX_MASK                              = 0xFFFF0000 # RAMP_AMAX_A1
	RAMP_AMAX_SHIFT                             = 16
	RAMP_D1_MASK                                = 0xFFFF # RAMP_DMAX_D1
	RAMP_D1_SHIFT                               = 0
	RAMP_DMAX_MASK                              = 0xFFFF0000 # RAMP_DMAX_D1
	RAMP_DMAX_SHIFT                             = 16
	RAMP_VSTART_MASK                            = 0x7FFFFF # RAMP_VSTART
	RAMP_VSTART_SHIFT                           = 0
	RAMP_V1_MASK                                = 0x7FFFFF # RAMP_V1
	RAMP_V1_SHIFT                               = 0
	RAMP_VSTOP_MASK                             = 0x7FFFFF # RAMP_VSTOP
	RAMP_VSTOP_SHIFT                            = 0
	STOP_L_ENABLE_MASK                          = 0x01 # RAMP_TZEROWAIT_SWITCHMODE
	STOP_L_ENABLE_SHIFT                         = 0
	STOP_R_ENABLE_MASK                          = 0x02 # RAMP_TZEROWAIT_SWITCHMODE
	STOP_R_ENABLE_SHIFT                         = 1
	POL_STOP_L_MASK                             = 0x04 # RAMP_TZEROWAIT_SWITCHMODE
	POL_STOP_L_SHIFT                            = 2
	POL_STOP_R_MASK                             = 0x08 # RAMP_TZEROWAIT_SWITCHMODE
	POL_STOP_R_SHIFT                            = 3
	SWAP_LR_MASK                                = 0x10 # RAMP_TZEROWAIT_SWITCHMODE
	SWAP_LR_SHIFT                               = 4
	LATCH_L_ACTIVE_MASK                         = 0x20 # RAMP_TZEROWAIT_SWITCHMODE
	LATCH_L_ACTIVE_SHIFT                        = 5
	LATCH_L_INACTIVE_MASK                       = 0x40 # RAMP_TZEROWAIT_SWITCHMODE
	LATCH_L_INACTIVE_SHIFT                      = 6
	LATCH_R_ACTIVE_MASK                         = 0x80 # RAMP_TZEROWAIT_SWITCHMODE
	LATCH_R_ACTIVE_SHIFT                        = 7
	LATCH_R_INACTIVE_MASK                       = 0x100 # RAMP_TZEROWAIT_SWITCHMODE
	LATCH_R_INACTIVE_SHIFT                      = 8
	EN_LATCH_ENCODER_MASK                       = 0x200 # RAMP_TZEROWAIT_SWITCHMODE
	EN_LATCH_ENCODER_SHIFT                      = 9
	SG_STOP_MASK                                = 0x400 # RAMP_TZEROWAIT_SWITCHMODE
	SG_STOP_SHIFT                               = 10
	EN_SOFTSTOP_MASK                            = 0x800 # RAMP_TZEROWAIT_SWITCHMODE
	EN_SOFTSTOP_SHIFT                           = 11
	RAMP_TZEROWAIT_MASK                         = 0xFFFF0000 # RAMP_TZEROWAIT_SWITCHMODE
	RAMP_TZEROWAIT_SHIFT                        = 16
	RAMP_X_ACTUAL_MASK                          = 0xFFFFFFFF # RAMP_X_ACTUAL
	RAMP_X_ACTUAL_SHIFT                         = 0
	RAMP_V_ACTUAL_MASK                          = 0xFFFFFFFF # RAMP_V_ACTUAL
	RAMP_V_ACTUAL_SHIFT                         = 0
	RAMP_X_TARGET_MASK                          = 0xFFFFFFFF # RAMP_X_TARGET
	RAMP_X_TARGET_SHIFT                         = 0
	RAMP_V_FEEDFORWARD_MASK                     = 0xFFFFFFFF # RAMP_V_FEEDFORWARD
	RAMP_V_FEEDFORWARD_SHIFT                    = 0
	OBSERVER_L_S_CROSS_MASK                     = 0xFFFF # OBSERVER_R_S_L_S_CROSS
	OBSERVER_L_S_CROSS_SHIFT                    = 0
	OBSERVER_R_S_MASK                           = 0xFFFF0000 # OBSERVER_R_S_L_S_CROSS
	OBSERVER_R_S_SHIFT                          = 16
	OBSERVER_L_SQ_MASK                          = 0xFFFF # OBSERVER_L_SD_L_SQ
	OBSERVER_L_SQ_SHIFT                         = 0
	OBSERVER_L_SD_MASK                          = 0xFFFF0000 # OBSERVER_L_SD_L_SQ
	OBSERVER_L_SD_SHIFT                         = 16
	OBSERVER_K_FILT_MASK                        = 0xFFFF # OBSERVER_K_EMF_INV_K_FILT
	OBSERVER_K_FILT_SHIFT                       = 0
	OBSERVER_K_EMF_INV_MASK                     = 0xFFFF0000 # OBSERVER_K_EMF_INV_K_FILT
	OBSERVER_K_EMF_INV_SHIFT                    = 16
	OBSERVER_K_D_MASK                           = 0xFFFF # OBSERVER_K_D
	OBSERVER_K_D_SHIFT                          = 0
	OBSERVER_E_SD_MASK                          = 0xFFFFFFFF # OBSERVER_E_SD
	OBSERVER_E_SD_SHIFT                         = 0
	OBSERVER_E_SQ_MASK                          = 0xFFFFFFFF # OBSERVER_E_SQ
	OBSERVER_E_SQ_SHIFT                         = 0
	OBSERVER_VELOCITY_MASK                      = 0xFFFFFFFF # OBSERVER_VELOCITY
	OBSERVER_VELOCITY_SHIFT                     = 0
	OBSERVER_PHI_E_MASK                         = 0xFFFF # OBSERVER_PHI_E
	OBSERVER_PHI_E_SHIFT                        = 0
	VELOCITY_SELECTION_MASK                     = 0xFF # VELOCITY_SELECTION
	VELOCITY_SELECTION_SHIFT                    = 0
	VELOCITY_METER_SYNC_PULSE_MASK              = 0x10000 # VELOCITY_SELECTION
	VELOCITY_METER_SYNC_PULSE_SHIFT             = 16
	VELOCITY_METER_DOWNSCALING_MASK             = 0xFF000000 # VELOCITY_SELECTION
	VELOCITY_METER_DOWNSCALING_SHIFT            = 24
	POSITION_SELECTION_MASK                     = 0xFF # POSITION_SELECTION
	POSITION_SELECTION_SHIFT                    = 0
	PHI_E_SELECTION_MASK                        = 0xFF # PHI_E_SELECTION
	PHI_E_SELECTION_SHIFT                       = 0
	PHI_E_MASK                                  = 0xFFFF # PHI_E
	PHI_E_SHIFT                                 = 0
	PID_FLUX_I_MASK                             = 0xFFFF # PID_FLUX_P_FLUX_I
	PID_FLUX_I_SHIFT                            = 0
	PID_FLUX_P_MASK                             = 0xFFFF0000 # PID_FLUX_P_FLUX_I
	PID_FLUX_P_SHIFT                            = 16
	PID_TORQUE_I_MASK                           = 0xFFFF # PID_TORQUE_P_TORQUE_I
	PID_TORQUE_I_SHIFT                          = 0
	PID_TORQUE_P_MASK                           = 0xFFFF0000 # PID_TORQUE_P_TORQUE_I
	PID_TORQUE_P_SHIFT                          = 16
	PID_VELOCITY_I_MASK                         = 0xFFFF # PID_VELOCITY_P_VELOCITY_I
	PID_VELOCITY_I_SHIFT                        = 0
	PID_VELOCITY_P_MASK                         = 0xFFFF0000 # PID_VELOCITY_P_VELOCITY_I
	PID_VELOCITY_P_SHIFT                        = 16
	PID_POSITION_I_MASK                         = 0xFFFF # PID_POSITION_P_POSITION_I
	PID_POSITION_I_SHIFT                        = 0
	PID_POSITION_P_MASK                         = 0xFFFF0000 # PID_POSITION_P_POSITION_I
	PID_POSITION_P_SHIFT                        = 16
	PID_POSITION_NORM_I_MASK                    = 0x80 # PID_TYPE
	PID_POSITION_NORM_I_SHIFT                   = 7
	PID_POSITION_NORM_P_MASK                    = 0x40 # PID_TYPE
	PID_POSITION_NORM_P_SHIFT                   = 6
	PID_VELOCITY_NORM_P_MASK                    = 0x20 # PID_TYPE
	PID_VELOCITY_NORM_P_SHIFT                   = 5
	PID_VELOCITY_NORM_I_MASK                    = 0x10 # PID_TYPE
	PID_VELOCITY_NORM_I_SHIFT                   = 4
	PID_CURRENT_CTRL_NORM_P_MASK                = 0x08 # PID_TYPE
	PID_CURRENT_CTRL_NORM_P_SHIFT               = 3
	PID_CURRENT_CTRL_NORM_I_MASK                = 0x04 # PID_TYPE
	PID_CURRENT_CTRL_NORM_I_SHIFT               = 2
	MODE_PID_SMPL_MASK                          = 0xFF00 # PID_TYPE
	MODE_PID_SMPL_SHIFT                         = 8
	MODE_FF_MASK                                = 0xFF0000 # PID_TYPE
	MODE_FF_SHIFT                               = 16
	PIDOUT_UQ_UD_LIMITS_MASK                    = 0xFFFF # PIDOUT_UQ_UD_LIMITS
	PIDOUT_UQ_UD_LIMITS_SHIFT                   = 0
	PID_TORQUE_FLUX_LIMITS_MASK                 = 0xFFFF # PID_TORQUE_FLUX_LIMITS
	PID_TORQUE_FLUX_LIMITS_SHIFT                = 0
	PID_ACCELERATION_LIMIT_MASK                 = 0xFFFFFFFF # PID_ACCELERATION_LIMIT
	PID_ACCELERATION_LIMIT_SHIFT                = 0
	PID_VELOCITY_LIMIT_MASK                     = 0xFFFFFFFF # PID_VELOCITY_LIMIT
	PID_VELOCITY_LIMIT_SHIFT                    = 0
	PID_POSITION_LIMIT_LOW_MASK                 = 0xFFFFFFFF # PID_POSITION_LIMIT_LOW
	PID_POSITION_LIMIT_LOW_SHIFT                = 0
	PID_POSITION_LIMIT_HIGH_MASK                = 0xFFFFFFFF # PID_POSITION_LIMIT_HIGH
	PID_POSITION_LIMIT_HIGH_SHIFT               = 0
	MODE_MOTION_MASK                            = 0x0F # MODE_RAMP_MODE_MOTION
	MODE_MOTION_SHIFT                           = 0
	MODE_RAMP_MASK                              = 0xF0 # MODE_RAMP_MODE_MOTION
	MODE_RAMP_SHIFT                             = 4
	POSITION_PRESCALER_MASK                     = 0xF00 # MODE_RAMP_MODE_MOTION
	POSITION_PRESCALER_SHIFT                    = 8
	PID_FLUX_TARGET_MASK                        = 0xFFFF # PID_TORQUE_FLUX_TARGET
	PID_FLUX_TARGET_SHIFT                       = 0
	PID_TORQUE_TARGET_MASK                      = 0xFFFF0000 # PID_TORQUE_FLUX_TARGET
	PID_TORQUE_TARGET_SHIFT                     = 16
	PID_FLUX_OFFSET_MASK                        = 0xFFFF # PID_TORQUE_FLUX_OFFSET
	PID_FLUX_OFFSET_SHIFT                       = 0
	PID_TORQUE_OFFSET_MASK                      = 0xFFFF0000 # PID_TORQUE_FLUX_OFFSET
	PID_TORQUE_OFFSET_SHIFT                     = 16
	PIDIN_FLUX_TARGET_MASK                      = 0xFFFF # PIDIN_TORQUE_FLUX_TARGET
	PIDIN_FLUX_TARGET_SHIFT                     = 0
	PIDIN_TORQUE_TARGET_MASK                    = 0xFFFF0000 # PIDIN_TORQUE_FLUX_TARGET
	PIDIN_TORQUE_TARGET_SHIFT                   = 16
	PID_VELOCITY_TARGET_MASK                    = 0xFFFFFFFF # PID_VELOCITY_TARGET
	PID_VELOCITY_TARGET_SHIFT                   = 0
	PID_VELOCITY_OFFSET_MASK                    = 0xFFFFFFFF # PID_VELOCITY_OFFSET
	PID_VELOCITY_OFFSET_SHIFT                   = 0
	PIDIN_VELOCITY_TARGET_MASK                  = 0xFFFFFFFF # PIDIN_VELOCITY_TARGET
	PIDIN_VELOCITY_TARGET_SHIFT                 = 0
	PID_POSITION_TARGET_MASK                    = 0xFFFFFFFF # PID_POSITION_TARGET
	PID_POSITION_TARGET_SHIFT                   = 0
	PID_FLUX_ACTUAL_MASK                        = 0xFFFF # PID_TORQUE_FLUX_ACTUAL
	PID_FLUX_ACTUAL_SHIFT                       = 0
	PID_TORQUE_ACTUAL_MASK                      = 0xFFFF0000 # PID_TORQUE_FLUX_ACTUAL
	PID_TORQUE_ACTUAL_SHIFT                     = 16
	PID_VELOCITY_ACTUAL_MASK                    = 0xFFFFFFFF # PID_VELOCITY_ACTUAL
	PID_VELOCITY_ACTUAL_SHIFT                   = 0
	PID_POSITION_ACTUAL_MASK                    = 0xFFFFFFFF # PID_POSITION_ACTUAL
	PID_POSITION_ACTUAL_SHIFT                   = 0
	PID_ERROR_PID_TORQUE_ERROR_MASK             = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_TORQUE_ERROR_SHIFT            = 0
	PID_ERROR_PID_FLUX_ERROR_MASK               = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_FLUX_ERROR_SHIFT              = 0
	PID_ERROR_PID_VELOCITY_ERROR_MASK           = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_VELOCITY_ERROR_SHIFT          = 0
	PID_ERROR_PID_POSITION_ERROR_MASK           = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_POSITION_ERROR_SHIFT          = 0
	PID_ERROR_PID_TORQUE_INTEGRATOR_MASK        = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_TORQUE_INTEGRATOR_SHIFT       = 0
	PID_ERROR_PID_FLUX_INTEGRATOR_MASK          = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_FLUX_INTEGRATOR_SHIFT         = 0
	PID_ERROR_PID_VELOCITY_INTEGRATOR_MASK      = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_VELOCITY_INTEGRATOR_SHIFT     = 0
	PID_ERROR_PID_POSITION_INTEGRATOR_MASK      = 0xFFFFFFFF # PID_ERROR_DATA
	PID_ERROR_PID_POSITION_INTEGRATOR_SHIFT     = 0
	PID_ERROR_ADDR_MASK                         = 0xFF # PID_ERROR_ADDR
	PID_ERROR_ADDR_SHIFT                        = 0
	INTERIM_PIDIN_TARGET_TORQUE_MASK            = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDIN_TARGET_TORQUE_SHIFT           = 0
	INTERIM_PIDIN_TARGET_FLUX_MASK              = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDIN_TARGET_FLUX_SHIFT             = 0
	INTERIM_PIDIN_TARGET_VELOCITY_MASK          = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDIN_TARGET_VELOCITY_SHIFT         = 0
	INTERIM_PIDIN_TARGET_POSITION_MASK          = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDIN_TARGET_POSITION_SHIFT         = 0
	INTERIM_PIDOUT_TARGET_TORQUE_MASK           = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDOUT_TARGET_TORQUE_SHIFT          = 0
	INTERIM_PIDOUT_TARGET_FLUX_MASK             = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDOUT_TARGET_FLUX_SHIFT            = 0
	INTERIM_PIDOUT_TARGET_VELOCITY_MASK         = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDOUT_TARGET_VELOCITY_SHIFT        = 0
	INTERIM_PIDOUT_TARGET_POSITION_MASK         = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_PIDOUT_TARGET_POSITION_SHIFT        = 0
	INTERIM_FOC_IUX_MASK                        = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_IUX_SHIFT                       = 0
	INTERIM_FOC_IWY_MASK                        = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_IWY_SHIFT                       = 16
	INTERIM_FOC_IV_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_IV_SHIFT                        = 0
	INTERIM_FOC_IA_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_IA_SHIFT                        = 0
	INTERIM_FOC_IB_MASK                         = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_IB_SHIFT                        = 16
	INTERIM_FOC_ID_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_ID_SHIFT                        = 0
	INTERIM_FOC_IQ_MASK                         = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_IQ_SHIFT                        = 16
	INTERIM_FOC_UD_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_UD_SHIFT                        = 0
	INTERIM_FOC_UQ_MASK                         = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_UQ_SHIFT                        = 16
	INTERIM_FOC_UD_LIMITED_MASK                 = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_UD_LIMITED_SHIFT                = 0
	INTERIM_FOC_UQ_LIMITED_MASK                 = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_UQ_LIMITED_SHIFT                = 16
	INTERIM_FOC_UA_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_UA_SHIFT                        = 0
	INTERIM_FOC_UB_MASK                         = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_UB_SHIFT                        = 16
	INTERIM_FOC_UUX_MASK                        = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_UUX_SHIFT                       = 0
	INTERIM_FOC_UWY_MASK                        = 0xFFFF0000 # INTERIM_DATA
	INTERIM_FOC_UWY_SHIFT                       = 16
	INTERIM_FOC_UV_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_FOC_UV_SHIFT                        = 0
	INTERIM_PWM_UX_MASK                         = 0xFFFF # INTERIM_DATA
	INTERIM_PWM_UX_SHIFT                        = 0
	INTERIM_PWM_WY_MASK                         = 0xFFFF0000 # INTERIM_DATA
	INTERIM_PWM_WY_SHIFT                        = 16
	INTERIM_PWM_V_MASK                          = 0xFFFF # INTERIM_DATA
	INTERIM_PWM_V_SHIFT                         = 0
	INTERIM_ADC_I_0_MASK                        = 0xFFFF # INTERIM_DATA
	INTERIM_ADC_I_0_SHIFT                       = 0
	INTERIM_ADC_I_1_MASK                        = 0xFFFF0000 # INTERIM_DATA
	INTERIM_ADC_I_1_SHIFT                       = 16
	INTERIM_ADC_I_2_MASK                        = 0xFFFF # INTERIM_DATA
	INTERIM_ADC_I_2_SHIFT                       = 0
	PID_VELOCITY_ACTUAL_DIV256_MASK             = 0xFFFF # INTERIM_DATA
	PID_VELOCITY_ACTUAL_DIV256_SHIFT            = 0
	PID_VELOCITY_TARGET_DIV256_MASK             = 0xFFFF0000 # INTERIM_DATA
	PID_VELOCITY_TARGET_DIV256_SHIFT            = 16
	PID_VELOCITY_ACTUAL_LSB_MASK                = 0xFFFF # INTERIM_DATA
	PID_VELOCITY_ACTUAL_LSB_SHIFT               = 0
	PID_VELOCITY_TARGET_LSB_MASK                = 0xFFFF0000 # INTERIM_DATA
	PID_VELOCITY_TARGET_LSB_SHIFT               = 16
	PID_POSITION_ACTUAL_DIV256_MASK             = 0xFFFF # INTERIM_DATA
	PID_POSITION_ACTUAL_DIV256_SHIFT            = 0
	PID_POSITION_TARGET_DIV256_MASK             = 0xFFFF0000 # INTERIM_DATA
	PID_POSITION_TARGET_DIV256_SHIFT            = 16
	PID_POSITION_ACTUAL_LSB_MASK                = 0xFFFF # INTERIM_DATA
	PID_POSITION_ACTUAL_LSB_SHIFT               = 0
	PID_POSITION_TARGET_LSB_MASK                = 0xFFFF0000 # INTERIM_DATA
	PID_POSITION_TARGET_LSB_SHIFT               = 16
	FF_VELOCITY_MASK                            = 0xFFFFFFFF # INTERIM_DATA
	FF_VELOCITY_SHIFT                           = 0
	FF_TORQUE_MASK                              = 0xFFFF # INTERIM_DATA
	FF_TORQUE_SHIFT                             = 0
	REF_SWITCH_STATUS_MASK                      = 0xFFFF # INTERIM_DATA
	REF_SWITCH_STATUS_SHIFT                     = 0
	HOME_POSITION_MASK                          = 0xFFFFFFFF # INTERIM_DATA
	HOME_POSITION_SHIFT                         = 0
	LEFT_POSITION_MASK                          = 0xFFFFFFFF # INTERIM_DATA
	LEFT_POSITION_SHIFT                         = 0
	RIGHT_POSITION_MASK                         = 0xFFFFFFFF # INTERIM_DATA
	RIGHT_POSITION_SHIFT                        = 0
	ENC_INIT_HALL_STATUS_MASK                   = 0xFFFF # INTERIM_DATA
	ENC_INIT_HALL_STATUS_SHIFT                  = 0
	ENC_INIT_HALL_PHI_E_ABN_OFFSET_MASK         = 0xFFFF # INTERIM_DATA
	ENC_INIT_HALL_PHI_E_ABN_OFFSET_SHIFT        = 0
	ENC_INIT_HALL_PHI_E_AENC_OFFSET_MASK        = 0xFFFF # INTERIM_DATA
	ENC_INIT_HALL_PHI_E_AENC_OFFSET_SHIFT       = 0
	ENC_INIT_HALL_PHI_A_AENC_OFFSET_MASK        = 0xFFFF # INTERIM_DATA
	ENC_INIT_HALL_PHI_A_AENC_OFFSET_SHIFT       = 0
	SINGLE_PIN_IF_INPUT_RAW_MASK                = 0xFFFF # INTERIM_DATA
	SINGLE_PIN_IF_INPUT_RAW_SHIFT               = 0
	SINGLE_PIN_IF_PWM_DUTY_CYCLE_MASK           = 0xFFFF0000 # INTERIM_DATA
	SINGLE_PIN_IF_PWM_DUTY_CYCLE_SHIFT          = 16
	SINGLE_PIN_IF_TORQUE_TARGET_MASK            = 0xFFFF # INTERIM_DATA
	SINGLE_PIN_IF_TORQUE_TARGET_SHIFT           = 0
	SINGLE_PIN_IF_VELOCITY_TARGET_MASK          = 0xFFFFFFFF # INTERIM_DATA
	SINGLE_PIN_IF_VELOCITY_TARGET_SHIFT         = 0
	SINGLE_PIN_IF_POSITION_TARGET_MASK          = 0xFFFFFFFF # INTERIM_DATA
	SINGLE_PIN_IF_POSITION_TARGET_SHIFT         = 0
	ABN_DECODER_PHI_M_RAW_MASK                  = 0xFFFF # INTERIM_DATA
	ABN_DECODER_PHI_M_RAW_SHIFT                 = 0
	SPI_ENCODER_PHI_M_RAW_MASK                  = 0xFFFF # INTERIM_DATA
	SPI_ENCODER_PHI_M_RAW_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_0_MASK                  = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_0_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_1_MASK                  = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_1_SHIFT                 = 16
	INTERIM_DEBUG_VALUE_2_MASK                  = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_2_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_3_MASK                  = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_3_SHIFT                 = 16
	INTERIM_DEBUG_VALUE_4_MASK                  = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_4_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_5_MASK                  = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_5_SHIFT                 = 16
	INTERIM_DEBUG_VALUE_6_MASK                  = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_6_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_7_MASK                  = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_7_SHIFT                 = 16
	INTERIM_DEBUG_VALUE_8_MASK                  = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_8_SHIFT                 = 0
	INTERIM_DEBUG_VALUE_9_MASK                  = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_9_SHIFT                 = 16
	INTERIM_DEBUG_VALUE_10_MASK                 = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_10_SHIFT                = 0
	INTERIM_DEBUG_VALUE_11_MASK                 = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_11_SHIFT                = 16
	INTERIM_DEBUG_VALUE_12_MASK                 = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_12_SHIFT                = 0
	INTERIM_DEBUG_VALUE_13_MASK                 = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_13_SHIFT                = 16
	INTERIM_DEBUG_VALUE_14_MASK                 = 0xFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_14_SHIFT                = 0
	INTERIM_DEBUG_VALUE_15_MASK                 = 0xFFFF0000 # INTERIM_DATA
	INTERIM_DEBUG_VALUE_15_SHIFT                = 16
	INTERIM_DEBUG_VALUE_16_MASK                 = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_16_SHIFT                = 0
	INTERIM_DEBUG_VALUE_17_MASK                 = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_17_SHIFT                = 0
	INTERIM_DEBUG_VALUE_18_MASK                 = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_18_SHIFT                = 0
	INTERIM_DEBUG_VALUE_19_MASK                 = 0xFFFFFFFF # INTERIM_DATA
	INTERIM_DEBUG_VALUE_19_SHIFT                = 0
	INTERIM_ADDR_MASK                           = 0xFF # INTERIM_ADDR
	INTERIM_ADDR_SHIFT                          = 0
	STEP_WIDTH_MASK                             = 0xFFFFFFFF # STEP_WIDTH
	STEP_WIDTH_SHIFT                            = 0
	UART_BPS_MASK                               = 0xFFFFFF # UART_BPS
	UART_BPS_SHIFT                              = 0
	ADDR_A_MASK                                 = 0xFF # UART_ADDRS
	ADDR_A_SHIFT                                = 0
	ADDR_B_MASK                                 = 0xFF00 # UART_ADDRS
	ADDR_B_SHIFT                                = 8
	ADDR_C_MASK                                 = 0xFF0000 # UART_ADDRS
	ADDR_C_SHIFT                                = 16
	ADDR_D_MASK                                 = 0xFF000000 # UART_ADDRS
	ADDR_D_SHIFT                                = 24
	GPIO_DSADCI_CONFIG_0_MASK                   = 0x01 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_0_SHIFT                  = 0
	GPIO_DSADCI_CONFIG_1_MASK                   = 0x02 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_1_SHIFT                  = 1
	GPIO_DSADCI_CONFIG_2_MASK                   = 0x04 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_2_SHIFT                  = 2
	GPIO_DSADCI_CONFIG_3_MASK                   = 0x08 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_3_SHIFT                  = 3
	GPIO_DSADCI_CONFIG_4_MASK                   = 0x10 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_4_SHIFT                  = 4
	GPIO_DSADCI_CONFIG_5_MASK                   = 0x20 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_5_SHIFT                  = 5
	GPIO_DSADCI_CONFIG_6_MASK                   = 0x40 # GPIO_dsADCI_CONFIG
	GPIO_DSADCI_CONFIG_6_SHIFT                  = 6
	GPO_MASK                                    = 0xFF0000 # GPIO_dsADCI_CONFIG
	GPO_SHIFT                                   = 16
	GPI_MASK                                    = 0xFF000000 # GPIO_dsADCI_CONFIG
	GPI_SHIFT                                   = 24
	WATCHDOG_CFG_MASK                           = 0x03 # WATCHDOG_CFG
	WATCHDOG_CFG_SHIFT                          = 0
	ADC_VM_LIMIT_LOW_MASK                       = 0xFFFF # ADC_VM_LIMITS
	ADC_VM_LIMIT_LOW_SHIFT                      = 0
	ADC_VM_LIMIT_HIGH_MASK                      = 0xFFFF0000 # ADC_VM_LIMITS
	ADC_VM_LIMIT_HIGH_SHIFT                     = 16
	A_OF_ABN_RAW_MASK                           = 0x01 # TMC4671_INPUTS_RAW
	A_OF_ABN_RAW_SHIFT                          = 0
	B_OF_ABN_RAW_MASK                           = 0x02 # TMC4671_INPUTS_RAW
	B_OF_ABN_RAW_SHIFT                          = 1
	N_OF_ABN_RAW_MASK                           = 0x04 # TMC4671_INPUTS_RAW
	N_OF_ABN_RAW_SHIFT                          = 2
	_MASK                                       = 0x08 # TMC4671_INPUTS_RAW
	_SHIFT                                      = 3
	A_OF_ABN_2_RAW_MASK                         = 0x10 # TMC4671_INPUTS_RAW
	A_OF_ABN_2_RAW_SHIFT                        = 4
	B_OF_ABN_2_RAW_MASK                         = 0x20 # TMC4671_INPUTS_RAW
	B_OF_ABN_2_RAW_SHIFT                        = 5
	N_OF_ABN_2_RAW_MASK                         = 0x40 # TMC4671_INPUTS_RAW
	N_OF_ABN_2_RAW_SHIFT                        = 6
	HALL_UX_OF_HALL_RAW_MASK                    = 0x100 # TMC4671_INPUTS_RAW
	HALL_UX_OF_HALL_RAW_SHIFT                   = 8
	HALL_V_OF_HALL_RAW_MASK                     = 0x200 # TMC4671_INPUTS_RAW
	HALL_V_OF_HALL_RAW_SHIFT                    = 9
	HALL_WY_OF_HALL_RAW_MASK                    = 0x400 # TMC4671_INPUTS_RAW
	HALL_WY_OF_HALL_RAW_SHIFT                   = 10
	REF_SW_R_RAW_MASK                           = 0x1000 # TMC4671_INPUTS_RAW
	REF_SW_R_RAW_SHIFT                          = 12
	REF_SW_H_RAW_MASK                           = 0x2000 # TMC4671_INPUTS_RAW
	REF_SW_H_RAW_SHIFT                          = 13
	REF_SW_L_RAW_MASK                           = 0x4000 # TMC4671_INPUTS_RAW
	REF_SW_L_RAW_SHIFT                          = 14
	ENI_RAW_MASK                                = 0x8000 # TMC4671_INPUTS_RAW
	ENI_RAW_SHIFT                               = 15
	STP_OF_DIRSTP_RAW_MASK                      = 0x10000 # TMC4671_INPUTS_RAW
	STP_OF_DIRSTP_RAW_SHIFT                     = 16
	DIR_OF_DIRSTP_RAW_MASK                      = 0x20000 # TMC4671_INPUTS_RAW
	DIR_OF_DIRSTP_RAW_SHIFT                     = 17
	PWM_IN_RAW_MASK                             = 0x40000 # TMC4671_INPUTS_RAW
	PWM_IN_RAW_SHIFT                            = 18
	HALL_UX_FILT_MASK                           = 0x100000 # TMC4671_INPUTS_RAW
	HALL_UX_FILT_SHIFT                          = 20
	HALL_V_FILT_MASK                            = 0x200000 # TMC4671_INPUTS_RAW
	HALL_V_FILT_SHIFT                           = 21
	HALL_WY_FILT_MASK                           = 0x400000 # TMC4671_INPUTS_RAW
	HALL_WY_FILT_SHIFT                          = 22
	PWM_IDLE_L_RAW_MASK                         = 0x10000000 # TMC4671_INPUTS_RAW
	PWM_IDLE_L_RAW_SHIFT                        = 28
	PWM_IDLE_H_RAW_MASK                         = 0x20000000 # TMC4671_INPUTS_RAW
	PWM_IDLE_H_RAW_SHIFT                        = 29
	_OUTPUTS_RAW_0_MASK                         = 0x01 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_0_SHIFT                        = 0
	_OUTPUTS_RAW_1_MASK                         = 0x02 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_1_SHIFT                        = 1
	_OUTPUTS_RAW_2_MASK                         = 0x04 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_2_SHIFT                        = 2
	_OUTPUTS_RAW_3_MASK                         = 0x08 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_3_SHIFT                        = 3
	_OUTPUTS_RAW_4_MASK                         = 0x10 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_4_SHIFT                        = 4
	_OUTPUTS_RAW_5_MASK                         = 0x20 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_5_SHIFT                        = 5
	_OUTPUTS_RAW_6_MASK                         = 0x40 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_6_SHIFT                        = 6
	_OUTPUTS_RAW_7_MASK                         = 0x80 # TMC4672_OUTPUTS_RAW
	_OUTPUTS_RAW_7_SHIFT                        = 7
	STATUS_FLAGS_0_MASK                         = 0x01 # STATUS_FLAGS
	STATUS_FLAGS_0_SHIFT                        = 0
	STATUS_FLAGS_1_MASK                         = 0x02 # STATUS_FLAGS
	STATUS_FLAGS_1_SHIFT                        = 1
	STATUS_FLAGS_2_MASK                         = 0x04 # STATUS_FLAGS
	STATUS_FLAGS_2_SHIFT                        = 2
	STATUS_FLAGS_3_MASK                         = 0x08 # STATUS_FLAGS
	STATUS_FLAGS_3_SHIFT                        = 3
	STATUS_FLAGS_4_MASK                         = 0x10 # STATUS_FLAGS
	STATUS_FLAGS_4_SHIFT                        = 4
	STATUS_FLAGS_5_MASK                         = 0x20 # STATUS_FLAGS
	STATUS_FLAGS_5_SHIFT                        = 5
	STATUS_FLAGS_6_MASK                         = 0x40 # STATUS_FLAGS
	STATUS_FLAGS_6_SHIFT                        = 6
	STATUS_FLAGS_7_MASK                         = 0x80 # STATUS_FLAGS
	STATUS_FLAGS_7_SHIFT                        = 7
	STATUS_FLAGS_8_MASK                         = 0x100 # STATUS_FLAGS
	STATUS_FLAGS_8_SHIFT                        = 8
	STATUS_FLAGS_9_MASK                         = 0x200 # STATUS_FLAGS
	STATUS_FLAGS_9_SHIFT                        = 9
	STATUS_FLAGS_10_MASK                        = 0x400 # STATUS_FLAGS
	STATUS_FLAGS_10_SHIFT                       = 10
	STATUS_FLAGS_11_MASK                        = 0x800 # STATUS_FLAGS
	STATUS_FLAGS_11_SHIFT                       = 11
	STATUS_FLAGS_12_MASK                        = 0x1000 # STATUS_FLAGS
	STATUS_FLAGS_12_SHIFT                       = 12
	STATUS_FLAGS_13_MASK                        = 0x2000 # STATUS_FLAGS
	STATUS_FLAGS_13_SHIFT                       = 13
	STATUS_FLAGS_14_MASK                        = 0x4000 # STATUS_FLAGS
	STATUS_FLAGS_14_SHIFT                       = 14
	STATUS_FLAGS_15_MASK                        = 0x8000 # STATUS_FLAGS
	STATUS_FLAGS_15_SHIFT                       = 15
	STATUS_FLAGS_16_MASK                        = 0x10000 # STATUS_FLAGS
	STATUS_FLAGS_16_SHIFT                       = 16
	STATUS_FLAGS_17_MASK                        = 0x20000 # STATUS_FLAGS
	STATUS_FLAGS_17_SHIFT                       = 17
	STATUS_FLAGS_18_MASK                        = 0x40000 # STATUS_FLAGS
	STATUS_FLAGS_18_SHIFT                       = 18
	STATUS_FLAGS_19_MASK                        = 0x80000 # STATUS_FLAGS
	STATUS_FLAGS_19_SHIFT                       = 19
	STATUS_FLAGS_20_MASK                        = 0x100000 # STATUS_FLAGS
	STATUS_FLAGS_20_SHIFT                       = 20
	STATUS_FLAGS_21_MASK                        = 0x200000 # STATUS_FLAGS
	STATUS_FLAGS_21_SHIFT                       = 21
	STATUS_FLAGS_22_MASK                        = 0x400000 # STATUS_FLAGS
	STATUS_FLAGS_22_SHIFT                       = 22
	STATUS_FLAGS_23_MASK                        = 0x800000 # STATUS_FLAGS
	STATUS_FLAGS_23_SHIFT                       = 23
	STATUS_FLAGS_24_MASK                        = 0x1000000 # STATUS_FLAGS
	STATUS_FLAGS_24_SHIFT                       = 24
	STATUS_FLAGS_25_MASK                        = 0x2000000 # STATUS_FLAGS
	STATUS_FLAGS_25_SHIFT                       = 25
	STATUS_FLAGS_26_MASK                        = 0x4000000 # STATUS_FLAGS
	STATUS_FLAGS_26_SHIFT                       = 26
	STATUS_FLAGS_27_MASK                        = 0x8000000 # STATUS_FLAGS
	STATUS_FLAGS_27_SHIFT                       = 27
	STATUS_FLAGS_28_MASK                        = 0x10000000 # STATUS_FLAGS
	STATUS_FLAGS_28_SHIFT                       = 28
	STATUS_FLAGS_29_MASK                        = 0x20000000 # STATUS_FLAGS
	STATUS_FLAGS_29_SHIFT                       = 29
	STATUS_FLAGS_30_MASK                        = 0x40000000 # STATUS_FLAGS
	STATUS_FLAGS_30_SHIFT                       = 30
	STATUS_FLAGS_31_MASK                        = 0x80000000 # STATUS_FLAGS
	STATUS_FLAGS_31_SHIFT                       = 31
	STATUS_MASK_MASK                            = 0xFFFFFFFF # STATUS_MASK
	STATUS_MASK_SHIFT                           = 0
