name: Manual Triggered Test

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
    - name: Install pytrinamic
      run: pip install .
    - name: Run the example tests
      working-directory: examples
      run: |
        pytest -v --html=pytest_examples_report.html
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: examples/pytest_examples_report.html

    