name: Push Triggered Testrun

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
    - name: Install pytrinamic from the checked out repository
      run: pip install .
    - name: Run the example tests
      working-directory: examples
      run: pytest -v --html=pytest_examples_report.html --self-contained-html
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: examples/pytest_examples_report.html

    